sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
script:
  - npm test
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
